package com.yinziming.part06.reverse.model;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.lastname
     *
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    private String lastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.department_id
     *
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    private Integer departmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.lastname
     *
     * @return the value of employee.lastname
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.lastname
     *
     * @param lastname the value for employee.lastname
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.department_id
     *
     * @return the value of employee.department_id
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.department_id
     *
     * @param departmentId the value for employee.department_id
     * @mbg.generated Fri Feb 19 14:29:54 CST 2021
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }
}